### ISSUE TITLE
Azure builder equivalent of source_ami_filter

### ISSUE THREAD

**Issue by paololazzari** [hashicorp/packer-plugin-azure#171]
Amazon EBS builder has the feature to filter AMIs by name. From the [docs](https://www.packer.io/docs/builders/amazon/ebs#source_ami_filter):

```json
"source_ami_filter": {
    "filters": {
       "virtualization-type": "hvm",
       "name": "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*",
       "root-device-type": "ebs"
    },
    "owners": ["099720109477"],
     "most_recent": true
}
```

This is really useful, especially when working with chained packer builds.

Is it possible to do the same in Azure? From my review of the [docs](https://www.packer.io/docs/builders/azure/arm#image_url), it doesn't seem possible right now.

Something like `source_vhd_filter` would be great to have.

**Comment by JenGoldstrich** [comment]
This is a great suggestion, I realize it's been a while with no response but just to clarify this is done in AWS by the Filter field on the endpoint https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html, I do not believe Azure has a concept similar to this for its endpoints so this is something we'd need to do custom which would mean doing a lot more read requests against a users resource group, which the service principal may not have access to. 

Because of this I don't think this is something we can support, sorry!
