### ISSUE TITLE
Missing option "temporary_key_pair_type" to enable Ubuntu 22.04 builds in Azure builder

### ISSUE THREAD

**Issue by ebrandsberg** [hashicorp/packer-plugin-azure#201]
Present in others, and needed for easy setup of Ubuntu 22.04 and other distributions that disable RSA by default:

Documented for the following builders that I noticed:

https://www.packer.io/plugins/builders/cloudstack#temporary_key_pair_type
https://www.packer.io/plugins/builders/openstack#temporary_key_pair_type
https://www.packer.io/plugins/builders/googlecompute#temporary_key_pair_type
https://www.packer.io/plugins/builders/amazon/ebs#temporary_key_pair_type
https://www.packer.io/plugins/builders/alicloud#temporary_key_pair_type

It is also missing in others however such as for Digital Ocean, hetzner-cloud, etc.

From the ssh communicator page @https://www.packer.io/docs/communicators/ssh:

"Note: SSH communicator options: ssh_keypair_name, ssh_agent_auth, temporary_key_pair_name and ssh_private_key_file are also supported by the communicator. But they may not be supported for every builder. Please check the builder specific documentation for additional SSH supported options."

Missing this functionality makes it much harder to setup base images.

**Comment by nywilken** [comment]
Hi folks, this issue should be resolved with the latest release of the Azure plugin and in Packer 1.8.1 for all plugins. Please upgrade to the latest release for the fix pertaining to the SSH RSA-SHA2 changes needed for Ubuntu Jammy. 

Regarding support for the `temporary_key_pair_type` configuration it is up to each builder to support it. It was not previously supported by default as each Cloud provider did not have support for setting custom key types. That has since change, which means we can work to update said builders if support is available. If you are interested in opening a PR with the changes to builders we would be more than happy to review and merge.

**Comment by tmeckel** [comment]
@nywilken Thanks for the quick and detailed answer. Much appreciated! 👍🏼

**Comment by nywilken** [comment]
Great to hear. Thanks for confirming the fix. I'll close the issue, as it has been resolved. Cheers!
