### ISSUE TITLE
packer-plugin-azure does not remove the datadisk after image creation.  How can the randomly named temporary datadisk be deleted?

### ISSUE THREAD

**Issue by jet4423** [hashicorp/packer-plugin-azure#277]
Issues on GitHub are intended to be related to bugs or feature requests, so we
recommend using our other community resources instead of asking here if you
have a question.

- Packer Guides: https://www.packer.io/guides
- Discussion List: https://groups.google.com/group/packer-tool
- Any other questions can be sent to the packer section of the HashiCorp
  forum: https://discuss.hashicorp.com/c/packer
- Packer community links: https://www.packer.io/community

**Comment by JenGoldstrich** [comment]
I believe this issue should be resolved in https://github.com/hashicorp/packer-plugin-azure/releases/tag/v1.4.3

A more detailed explanation can be found here https://github.com/hashicorp/packer-plugin-azure/issues/125#issuecomment-1587938709 but the TL;Dr is that the plugin was incorrectly trying to delete the OS disk for the Key Vault we create for Windows builds, KeyVaults do not have disks so this was just incorrect logic which is why we'd always log that we failed to delete this disk.

If you are still seeing this issue on v1.4.3 of the Azure plugin please re-open this issue.
