### ISSUE TITLE
missing output from azure packer build

### ISSUE THREAD

**Issue by chalecado** [hashicorp/packer-plugin-azure#348]
Hi

Using version 2.0.0 and 2.0.1 we are missing the output of some values we use

I have reverted back down to 1.0 i believe and it works again

The values no longer outputting are

OSDiskUriReadOnlySas
TemplateUriReadOnlySas

**Comment by lbajolet-hashicorp** [comment]
Hi @chalecado,

This change was introduced in v2.0.0 of the plugin, and is intended; refer to the [release notes](https://github.com/hashicorp/packer-plugin-azure/releases/tag/v2.0.0), specifically the `SAS URIs` section for more information.

As this is the expected behaviour here, I'll relabel your PR to not-a-bug, please feel free to correct me if I misunderstood the issue.

Thanks!

(cc @JenGoldstrich if you have something to add for context/mitigation)
